[package]
name = "joueur"
edition = "2018"
version = "0.1.0"
authors = [
    "Jacob Fischer <jacob.t.fischer@gmail.com>",
    "Russley Shaw <russleyshaw@gmail.com>",
]

[dependencies]
clap = "2.33.0"
serde = "1.0.104"
serde_json = "1.0.44"
termcolor = "1.1"
